alias tree="tree -CA"
alias gs="git status"
alias gac="git add . && git commit -m"
alias gacam="git add . && git commit --amend"
alias gp="git push"
alias gl="git pull"
alias gcb="git checkout -b"
alias go="git checkout"
alias gd="git diff"
alias glo="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
